spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/gikhub
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
      show_sql: true
      properties:
        hibernate:
      logging.level:
        org.hibernate.SQL: debug
        org.hibernate.type: trace
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

server:
  servlet:
    session:
      timeout: 30m
      tracking-modes: cookie
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /v1/**